name: Deploy Event Registration App

on:
  push:
    branches:
      - main  # Deploy when code is pushed to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./api
        run: npm install

      # Deploy Frontend + API to Azure Static Web Apps
      - name: Deploy Frontend & API
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.cdea8b22b6a14610cdcc7bc5aa25cbcf88dafa45ea84685178b04384ea04526f02-5f572ebf-c37f-486e-b833-52f851f8a9a801e2704013a30f1e }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          api_location: "api"
          output_location: "build"   # set this if React, leave "" for plain HTML

      # Deploy Azure Functions separately (optional)
      - name: Deploy Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "eventregdb123"   # Replace with your Azure Function App name
          package: ./api
